name: fb_auth_riverpod
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_messaging: ^14.9.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.0
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  geolocator: ^11.0.0
  go_router: ^11.0.0
  lottie: ^3.1.0
  riverpod_annotation: ^2.1.5
  url_strategy: ^0.2.0
  validators: ^3.0.0
  latlong2: ^0.9.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
