// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATdG5IDPSUZOwHCcO6l9izsNIO-K5VX8k',
    appId: '1:1047650580488:web:e46942f598c4b58b4379bd',
    messagingSenderId: '1047650580488',
    projectId: 'fb-auth-rivepod-ksl2024',
    authDomain: 'fb-auth-rivepod-ksl2024.firebaseapp.com',
    storageBucket: 'fb-auth-rivepod-ksl2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBosKLsjkKhgj2qo1Te4wS9Ph6YT5o18Fs',
    appId: '1:1047650580488:android:cfd3b090f3b3a0864379bd',
    messagingSenderId: '1047650580488',
    projectId: 'fb-auth-rivepod-ksl2024',
    storageBucket: 'fb-auth-rivepod-ksl2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrSay8fukBfNaCKsbSZaWWnEFlw8G8ri4',
    appId: '1:1047650580488:ios:aacbf502e7de3b9e4379bd',
    messagingSenderId: '1047650580488',
    projectId: 'fb-auth-rivepod-ksl2024',
    storageBucket: 'fb-auth-rivepod-ksl2024.appspot.com',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );

}